web:
  build: .
  working_dir: /data
  command: python app.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5050"

db:
  image: postgres:9.3
  environment:
    - POSTGRES_USER=sys_web
    - POSTGRES_PASSWORD=123
  ports:
    - "5432:5432"